### ISSUE TITLE
d1w19 开智苏州首次线下聚会回顾帖

### ISSUE THREAD

**Issue by zhb6696** [zhb6696/Open-Mind-Suzhou#1]
D1W19开智苏州线下聚会回顾
参加同学：
Irene:产品部落1期&认知写作学4期学员；互联网行业产品经理
Verunft（张云帆）：通识部落3期，房地产行业
赵庶剑：通识部落1期，风电行业
Brady（朱红波）：通识部落2期，医药行业采购
议题回顾：
1. 线下活动安排：活动频次每2月一次，可以拟一个主题，每个人进行各自的分享。每次分享后，在Git Hub仓库上传活动回顾和收获
2. 线上活动以卡片交流为主，在开智平台提交卡片后，在微信群中发出连接，其他学友可以进行跟帖回复。
个人收获：
1. 活动组织还是不太充分，以后活动的组织者最好还是按照标准的活动流程把活动环节做好，让讨论更加充分，也让参加者更有收获
2. Irene再次强调了最小行动这个原则，写卡片或其他任务，一定是先完成再完善，完成一次最小行动是最重要的。
欢迎大家发表此次聚会的回顾

**Comment by shujianzhao** [comment]
## 工具交流
1. [raindrop](https://raindrop.io/) 网页管理类应用，可用于管理收藏的网页。补充一个我用过的类似网站：[pocket](https://getpocket.com/)。
2. 卡片编辑：[gitbook editor](https://www.gitbook.com/editor) 可以当作书写卡片的IDE。
说下我的工具：Markdown编辑器--Typora，Blog客户端：MarkEditor，个人非常喜爱它的“一键wiki”功能。

**Comment by Irene6161** [comment]
### 关于自己在开智的收获

- 承认自己的不足之处
面对巨大的听同侪压力，被压倒之前，自己先调整好心态摆好位置

- 看见自己的成长
并非自暴自弃，而是和过去的自己相比

- 找到自己的内在动机
找到自己的内在动机，保护好自己的内在动机

- 减少无效的社交保护好自己的时间
专注于作品之上

=========================

大家叫我六一就好，这样比较容易记啊。
